<?php
/**
 * Location Archive Template
 * Template for displaying location taxonomy archive with business hours
 * 
 * @package Multi_Location_Product_Inventory_Management
 */

if (!defined('ABSPATH')) exit;

$mulopimfwc_location_archive_enqueue_registered_assets = static function ($handles, $type) {
    foreach ((array) $handles as $handle) {
        $handle = is_string($handle) ? trim($handle) : '';

        if ($handle === '') {
            continue;
        }

        if ($type === 'style') {
            if (wp_style_is($handle, 'registered') || wp_style_is($handle, 'enqueued')) {
                wp_enqueue_style($handle);
            }

            continue;
        }

        if (wp_script_is($handle, 'registered') || wp_script_is($handle, 'enqueued')) {
            wp_enqueue_script($handle);
        }
    }
};

add_action(
    'wp_enqueue_scripts',
    static function () use ($mulopimfwc_location_archive_enqueue_registered_assets) {
        if (!apply_filters('mulopimfwc_location_archive_enqueue_theme_filter_assets', true)) {
            return;
        }

        $mulopimfwc_location_archive_enqueue_registered_assets(
            apply_filters('mulopimfwc_location_archive_filter_script_handles', [
                'wd-filters-area',
            ]),
            'script'
        );

        $mulopimfwc_location_archive_enqueue_registered_assets(
            apply_filters('mulopimfwc_location_archive_filter_style_handles', [
                'wd-shop-filter-area',
                'wd-widget-price-filter',
                'wd-widget-layered-nav-stock-status',
                'wd-widget-wd-layered-nav',
                'wd-widget-product-cat',
                'wd-select2',
            ]),
            'style'
        );
    },
    1000
);

get_header('shop');

/**
 * Hook: mulopimfwc_before_main_content
 */
do_action('mulopimfwc_before_main_content');

$mulopimfwc_location_archive_sidebar = '';

if (apply_filters('mulopimfwc_location_archive_show_sidebar', true)) {
    ob_start();
    do_action('woocommerce_sidebar');
    $mulopimfwc_location_archive_sidebar = trim(ob_get_clean());
}

$mulopimfwc_location_archive_has_sidebar = $mulopimfwc_location_archive_sidebar !== '';
$mulopimfwc_location_archive_layout_classes = [
    'mulopimfwc-location-shop-layout',
    $mulopimfwc_location_archive_has_sidebar ? 'mulopimfwc-location-shop-layout--has-sidebar' : 'mulopimfwc-location-shop-layout--no-sidebar',
];

$mulopimfwc_location_archive_get_filter_area = static function () {
    $filter_area_callbacks = apply_filters('mulopimfwc_location_archive_filter_area_callbacks', []);

    foreach ((array) $filter_area_callbacks as $filter_area_callback) {
        if (!is_callable($filter_area_callback)) {
            continue;
        }

        ob_start();
        $filter_area_result = call_user_func($filter_area_callback);
        $filter_area_html = trim(ob_get_clean());

        if (is_string($filter_area_result)) {
            $filter_area_html .= trim($filter_area_result);
        }

        if ($filter_area_html !== '') {
            return $filter_area_html;
        }
    }

    $filter_sidebar_ids = apply_filters('mulopimfwc_location_archive_filter_sidebar_ids', [
        'filters-area',
        'shop-filters',
        'shop-filters-area',
        'shop_filters',
        'shop_filters_area',
        'woocommerce-filters',
        'woocommerce_filters',
    ]);

    foreach ((array) $filter_sidebar_ids as $filter_sidebar_id) {
        $filter_sidebar_id = is_string($filter_sidebar_id) ? trim($filter_sidebar_id) : '';

        if ($filter_sidebar_id === '' || !is_active_sidebar($filter_sidebar_id)) {
            continue;
        }

        ob_start();
        dynamic_sidebar($filter_sidebar_id);
        $filter_widgets_html = trim(ob_get_clean());

        if ($filter_widgets_html === '') {
            continue;
        }

        ob_start();
        ?>
        <div class="filters-area" style="display: none;">
            <div class="filters-inner-area wd-grid-g" style="--wd-col-lg:6;--wd-col-md:2;--wd-col-sm:1;--wd-gap-lg:30px;--wd-gap-sm:20px;">
                <?php
                // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Widget markup is generated by WordPress/theme callbacks.
                echo $filter_widgets_html;
                ?>
            </div>
        </div>
        <?php

        $filter_area_html = trim(ob_get_clean());

        return apply_filters('mulopimfwc_location_archive_filter_area_html', $filter_area_html, $filter_sidebar_id);
    }

    return '';
};

$mulopimfwc_location_archive_render_before_shop_loop = static function () use ($mulopimfwc_location_archive_get_filter_area) {
    ob_start();
    do_action('woocommerce_before_shop_loop');
    $before_shop_loop_html = trim(ob_get_clean());

    if ($before_shop_loop_html !== '') {
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- WooCommerce/theme callbacks render trusted shop-loop markup.
        echo $before_shop_loop_html;
    }

    $needs_filter_area = $before_shop_loop_html !== ''
        && false !== strpos($before_shop_loop_html, 'open-filters')
        && false === strpos($before_shop_loop_html, 'filters-area');

    $needs_filter_area = (bool) apply_filters(
        'mulopimfwc_location_archive_should_render_filter_area',
        $needs_filter_area,
        $before_shop_loop_html
    );

    if (!$needs_filter_area) {
        return;
    }

    $filter_area_html = $mulopimfwc_location_archive_get_filter_area();

    if ($filter_area_html === '') {
        return;
    }

    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Filter area markup is generated by WordPress/theme callbacks.
    echo $filter_area_html;
};

?>

<div class="mulopimfwc-location-archive-wrapper woocommerce">
    
    <?php if (have_posts()) : ?>

        <header class="mulopimfwc-location-archive-header">
            <?php
            /**
             * Hook: mulopimfwc_store_location_description_before_loop
             * 
             * @hooked MULOPIMFWC_Frontend_Location_Information::display_location_archive_info - 10
             */
            do_action('mulopimfwc_store_location_description_before_loop');
            ?>
        </header>

        <?php
        /**
         * Hook: mulopimfwc_before_location_products
         */
        do_action('mulopimfwc_before_location_products');
        ?>

        <div class="<?php echo esc_attr(implode(' ', $mulopimfwc_location_archive_layout_classes)); ?>">

            <?php if ($mulopimfwc_location_archive_has_sidebar) : ?>
                <aside class="mulopimfwc-location-shop-sidebar" aria-label="<?php echo esc_attr__('Shop sidebar', 'multi-location-product-and-inventory-management-pro'); ?>">
                    <?php
                    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Sidebar widgets are rendered by registered WooCommerce/theme callbacks.
                    echo $mulopimfwc_location_archive_sidebar;
                    ?>
                </aside>
            <?php endif; ?>

            <div class="mulopimfwc-location-shop-main">

                <div class="mulopimfwc-location-products">

                    <?php
                    /**
                     * Hook: woocommerce_before_shop_loop
                     *
                     * @hooked woocommerce_result_count - 20
                     * @hooked woocommerce_catalog_ordering - 30
                     */
                    $mulopimfwc_location_archive_render_before_shop_loop();
                    ?>

                    <?php
                    woocommerce_product_loop_start();

                    while (have_posts()) :
                        the_post();

                        /**
                         * Hook: woocommerce_shop_loop
                         */
                        do_action('woocommerce_shop_loop');

                        wc_get_template_part('content', 'product');

                    endwhile;

                    woocommerce_product_loop_end();
                    ?>

                    <?php
                    /**
                     * Hook: woocommerce_after_shop_loop
                     *
                     * @hooked woocommerce_pagination - 10
                     */
                    do_action('woocommerce_after_shop_loop');
                    ?>

                </div>

                <?php
                /**
                 * Hook: mulopimfwc_after_location_products
                 */
                do_action('mulopimfwc_after_location_products');
                ?>

            </div>

        </div>

    <?php else : ?>

        <div class="<?php echo esc_attr(implode(' ', $mulopimfwc_location_archive_layout_classes)); ?>">

            <?php if ($mulopimfwc_location_archive_has_sidebar) : ?>
                <aside class="mulopimfwc-location-shop-sidebar" aria-label="<?php echo esc_attr__('Shop sidebar', 'multi-location-product-and-inventory-management-pro'); ?>">
                    <?php
                    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Sidebar widgets are rendered by registered WooCommerce/theme callbacks.
                    echo $mulopimfwc_location_archive_sidebar;
                    ?>
                </aside>
            <?php endif; ?>

            <div class="mulopimfwc-location-shop-main">
                <div class="mulopimfwc-location-products mulopimfwc-location-products--empty">
                    <?php
                    /**
                     * Hook: woocommerce_no_products_found
                     *
                     * @hooked wc_no_products_found - 10
                     */
                    do_action('woocommerce_no_products_found');
                    ?>
                </div>
            </div>

        </div>

    <?php endif; ?>

</div>

<?php

/**
 * Hook: mulopimfwc_after_main_content
 */
do_action('mulopimfwc_after_main_content');

get_footer('shop');
